fix: lock only confirmed outputs (#37)
Description
---

The wallet will lock only UTXOs that satisfy the provided **confirmation
window**.

<img width="598" height="315" alt="Screenshot 2025-12-15 at 15 50 57"
src="https://github.com/user-attachments/assets/7c290d68-860b-4200-9232-b358e891aabf"
/>

Fixes: #34 


Motivation and Context
---

As of now, the `InputSelector` would use any unspent UTXOs. It did not
check if it is confirmed at all.

How Has This Been Tested?
---

```sh
$ cargo run --bin minotari   -- balance
Fetching balance...
Balance at height 190661(2025-10-02 13:10:15): 335,446,266,385 microTari (335,446.266,385 Tari)
```

```sh
$ cargo run --bin minotari   -- lock-funds -a default -m 1000 --confirmation-window 10000000
Locking funds...
Error: Failed to lock funds: Not enough funds. Available: 0 µT, required: 1000 µT
```

```sh
$ cargo run --bin minotari   -- lock-funds -a default -m 1000 --confirmation-window 3
Locking funds...
Locked funds output written to file
```

What process can a PR reviewer use to test or verify this change?
---

<!-- Checklist -->
<!-- 1. Is the title of your PR in the form that would make nice release
notes? The title, excluding the conventional commit
tag, will be included exactly as is in the CHANGELOG, so please think
about it carefully. -->


Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

<!-- Does this include a breaking change? If so, include this line as a
footer -->
<!-- BREAKING CHANGE: Description what the user should do, e.g. delete a
database, resync the chain -->