feat: support multiple wallet types (#46)
Description
---

Adds support for multiple wallet types.
Will use `aegon2` for KDF.

Adds CLI commands:
- `show-keys` (shows private view and public spend keys)
- `show-seed-words` (shows seed words if wallet has seed words type)
- `create` (creates a *seed words* wallet)

Closes #44 

How Has This Been Tested?
---

### Create a wallet using view/spend keys

```sh
$ cargo run --bin minotari -- import-view-key   --view-private-key 4b511bfd7f8657a95ef9ac08cf46bb645c30df09c8314762bb91588db12f070a   --spend-public-key 504b663c96ca23722760e76b73f6e61bde7ad40746505a3b
106f0327460e9e7f   --password password
11:39 INFO  Importing wallet view_key=4b511b...2f070a spend_key=504b66...0e9e7f
11:39 ERROR database is locked
11:39 ERROR database is locked
11:39 INFO  Database migrated to version 20
11:39 INFO  DB: Creating new account account=default
```

### Scan

```sh
$ cargo run --bin minotari   -- scan --password password --max-blocks-to-scan 500000 --base-url https://rpc.esmeralda.tari.com
11:40 INFO  Scanning blockchain...
11:40 INFO  Starting scan for account account_id=1 start_height=0
11:40 INFO  Processing scanned blocks count=25 account_id=1
11:40 INFO  Processing scanned blocks count=25 account_id=1
11:40 INFO  Processing scanned blocks count=25 account_id=1
11:40 INFO  Processing scanned blocks count=25 account_id=1

...

11:41 INFO  Detected wallet output account_id=1 block_height=12862 value=<REDACTED> is_coinbase=false
11:41 INFO  DB: Inserting output account_id=1 value=<REDACTED> height=12862
11:41 INFO  DB: Inserting wallet event account_id=1 event_type=OutputDetected
11:41 INFO  Output confirmed account_id=1 output_hash=9ea49e...caa568 original_height=12862 confirmed_at=12865
11:41 INFO  DB: Inserting wallet event account_id=1 event_type=OutputConfirmed
11:41 INFO  DB: Output Confirmed height=12865
11:41 INFO  Detected wallet output account_id=1 block_height=12871 value=<REDACTED> is_coinbase=false
11:41 INFO  DB: Inserting output account_id=1 value=<REDACTED> height=12871
...
```

### Get balance

```sh
$ cargo run --bin minotari   -- balance
11:41 INFO  Fetching balance...
Balance at height 12917(2025-05-27 10:55:10): 745,341,256,101 microTari (745,341.256,101 Tari)
```

### Export view/spend keys

```sh
$ cargo run --bin minotari   -- show-keys --password password
11:45 INFO  Retrieving wallet keys...
---------------------------------------------------------
Wallet           : default
Private View Key : 4b511bfd7f8657a95ef9ac08cf46bb645c30df09c8314762bb91588db12f070a
Public Spend Key : 504b663c96ca23722760e76b73f6e61bde7ad40746505a3b106f0327460e9e7f
---------------------------------------------------------
WARNING: Keep your private view key safe. Anyone with it can see your transaction history.
```

### Create a `seeds words` account

```sh
$ cargo run --bin minotari   -- create -p passowrd -a full_account
11:46 INFO  Initializing Seed Words Wallet...
11:46 INFO  Generating new random seed...
11:46 INFO  DB: Creating new account account=full_account
11:46 INFO  Wallet initialized successfully
```

### Export seed words

```
$ cargo run --bin minotari   -- show-seed-words -p passowrd -a full_account
11:47 INFO  Retrieving seed words...
---------------------------------------------------------
Wallet: full_account
Seed Words: scare oil wink pluck between bonus truth fall apology hello bright excite sauce raise twist beauty thank only private festival unable exchange maze enter
---------------------------------------------------------
WARNING: Keep these words safe. Anyone with them can spend your funds
```

### Fails to create a wallet with the same **fingerprint**

```sh
$ cargo run --bin minotari   -- create -p passowrd -a full_account2 -s "scare oil wink pluck between bonus truth fall apology hello bright excite sauce raise twist beauty thank only private festival unable exchange maze enter"
11:48 INFO  Initializing Seed Words Wallet...
11:48 INFO  Restoring from provided seed words...
11:48 INFO  DB: Creating new account account=full_account2
Error: Database execution error: UNIQUE constraint failed: accounts.fingerprint

Caused by:
    0: UNIQUE constraint failed: accounts.fingerprint
    1: Error code 2067: A UNIQUE constraint failed
```

<!-- Checklist -->
<!-- 1. Is the title of your PR in the form that would make nice release notes? The title, excluding the conventional commit
tag, will be included exactly as is in the CHANGELOG, so please think about it carefully. -->


Breaking Changes
---

- [x] None
- [ ] Requires data directory on base node to be deleted
- [ ] Requires hard fork
- [ ] Other - Please specify

<!-- Does this include a breaking change? If so, include this line as a footer -->
<!-- BREAKING CHANGE: Description what the user should do, e.g. delete a database, resync the chain -->